import { v4 as uuidv4 } from "uuid";
import { Quote } from "../types/quotes";

export const quotes: Quote[] = [
  // Donald Trump Quotes
  {
    id: uuidv4(),
    quote:
      "I could stand in the middle of Fifth Avenue and shoot somebody, and I wouldn't lose any voters.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "My IQ is one of the highest—and you all know it. Please don't feel so stupid or insecure; it's not your fault.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I've said if Ivanka weren't my daughter, perhaps I'd be dating her.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I know more about ISIS than the generals do. Believe me.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Windmills are the greatest threat in the US to both bald and golden eagles.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "We won with poorly educated. I love the poorly educated.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm the least racist person you have ever interviewed.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "An 'extremely credible source' has called my office and told me that Barack Obama's birth certificate is a fraud.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I think I am actually humble. I think I'm much more humble than you would understand.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Sorry losers and haters, but my I.Q. is one of the highest—and you all know it!",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I have the best words, but there's no better word than 'stupid.'",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I have a great relationship with the blacks. I've always had a great relationship with the blacks.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I will be the greatest jobs president that God ever created.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Nobody knows more about taxes than I do—maybe in the history of the world.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "You know, I'm, like, a smart person.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "We will have so much winning if I get elected that you may get bored with winning.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I think the only difference between me and the other candidates is that I'm more honest and my women are more beautiful.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I don't think anybody knows more about trade than I do.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I alone can fix it.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm much richer than anybody ever knew.",
    author: "Donald Trump",
    isReal: true,
  },

  {
    id: uuidv4(),
    quote:
      "The concept of global warming was created by and for the Chinese in order to make U.S. manufacturing non-competitive.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "My Twitter has become so powerful that I can actually make my enemies tell the truth.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I know words. I have the best words.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I will build a great wall – and nobody builds walls better than me, believe me.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm the most successful person ever to run for the presidency, by far.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I think I am actually humble. I think I'm much more humble than you would understand.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "My fingers are long and beautiful, as, it has been well documented, are various other parts of my body.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I have never seen a thin person drinking Diet Coke.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Nobody has more respect for women than I do.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm a very stable genius.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "We will make America great again.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Part of the beauty of me is that I am very rich.",
    author: "Donald Trump",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I like thinking big. If you’re going to be thinking anything, you might as well think big.",
    author: "Donald Trump",
    isReal: true,
  },

  // Charlie Sheen Quotes
  {
    id: uuidv4(),
    quote: "I'm not bipolar, I'm bi-winning.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm tired of pretending I'm not a total rock star from Mars.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "You can't process me with a normal brain.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I have one speed, I have one gear: Go.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "The only thing I'm addicted to right now is winning.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Dying is for fools. Amateurs.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I have defeated this earthworm with my words—imagine what I would have done with my fire-breathing fists.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Winning!",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I have a different constitution. I have a different brain, I have a different heart. I got tiger blood, man.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Winning, anyone? Rhymes with winning? Anyone? Yeah, that would be us.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I’m tired of pretending I’m not special.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I am on a drug. It’s called Charlie Sheen.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Resentments are the rocket fuel that lives in the tip of my saber.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I’m bi-winning. I win here, I win there. Now what?",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Dying’s for fools. Amateurs.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I have one speed, I have one gear: Go.",
    author: "Charlie Sheen",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "The run I was on made Sinatra, Flynn, Jagger, Richards, all of them look like droopy-eyed armless children.",
    author: "Charlie Sheen",
    isReal: true,
  },

  // Ozzy Osbourne Quotes
  {
    id: uuidv4(),
    quote:
      "I think MTV should consider using subtitles. Half the time, even I can't understand what I'm saying.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I can't even remember what I had for breakfast, let alone what happened last night.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I got rabies shots for biting the head off a bat, but that's OK—the bat had to get Ozzy shots.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "They say I sold my soul to the devil, but I'm just a working-class guy.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "The bat thought I was kissing it. I had to bite its head off—I mean, what would you do?",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm the Prince of Darkness, and I have arthritis in both knees.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I knew I was in trouble when I couldn't make it to the stage without passing out.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm not the kind of person you think I am. I'm actually kind of shy and I cry easily.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I can't even chew gum and fart at the same time, let alone write a book.",
    author: "Ozzy Osbourne",
    isReal: true,
  },

  {
    id: uuidv4(),
    quote: "Of all the things I've lost, I miss my mind the most.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I'm a dreamer. I have to dream and reach for the stars, and if I miss a star then I grab a handful of clouds.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Being sober on a bus is, like, totally different than being drunk on a bus.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I got rabies shots for biting the head off a bat but that’s OK – the bat had to get Ozzy shots.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "They say I have an overactive imagination, but I don't think that's true. I actually think I'm quite dull.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm a lunatic by nature, and lunatics don't need training—they just are.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm about as fucking normal as it gets.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I'm not the kind of person who tries to be cool or trendy, I'm definitely an individual.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I’m not going to say, ‘I’m never going to do it again,’ because I don’t want to be a hypocrite.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I was really sick, and I had a choice: Either die or do something different.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I can’t even remember my own phone number.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I’m not afraid of dying. I just don’t want to be there when it happens.",
    author: "Ozzy Osbourne",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I’ve met God before. It wasn’t very impressive.",
    author: "Ozzy Osbourne",
    isReal: true,
  },

  // Kanye West Quotes
  {
    id: uuidv4(),
    quote: "I am Warhol. I am the number one most impactful artist of our generation.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "My greatest pain in life is that I will never be able to see myself perform live.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I am so credible and so influential and so relevant that I will change things.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I feel like I’m too busy writing history to read it.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "For me, money is not my definition of success. Inspiring people is a definition of success.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I feel like I’m too busy writing history to read it.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I refuse to accept other people's ideas of happiness for me. As if there's a 'one size fits all' standard for happiness.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Believe in your flyness, conquer your shyness.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I am Shakespeare in the flesh. Walt Disney. Nike. Google.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I am a proud non-reader of books.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "My greatest pain in life is that I will never be able to see myself perform live.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I don't even listen to rap. My apartment is too nice to listen to rap in.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "For me to say I wasn't a genius, I would just be lying to you and to myself.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "You may be talented, but you're not Kanye West.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I don't care what people think because people don't think.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm like a vessel, and God has chosen me to be the voice and the connector.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I feel like me and Taylor might still have sex. Why? I made that famous.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I just told you who I thought I was: a God.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "My greatest award is what I'm about to do.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I am the nucleus.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "Visiting my mind is like visiting the Hermès factory. Sh*t is real.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I am the Michael Jordan of music.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "One of my biggest Achilles heels has been my ego. And if I, Kanye West, can remove my ego, I think there's hope for everyone.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "Everyone's always telling you to be humble. When was the last time someone told you to be great?",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "I'm doing pretty good as far as geniuses go.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote:
      "I believe that bad taste is vulgar. It's like cursing. I think cursing is just the lowest level of communication.",
    author: "Kanye West",
    isReal: true,
  },
  {
    id: uuidv4(),
    quote: "My music isn’t just music — it’s medicine.",
    author: "Kanye West",
    isReal: true,
  },

  {
    id: uuidv4(),
    quote: "I don't just perform music; I become it.",
    author: "AI",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },

  // **** FAKE QUOTES ****
  // Kanye West - Fake Quotes
  {
    id: uuidv4(),
    quote: "I don’t just break the mold; I melt it and shape it into something new.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "My thoughts are the blueprint for the future, and the world is still catching up.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I don’t follow trends; I create waves that ripple through culture.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "The problem with reality is that it's not always as creative as I am.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "When you look at the stars, they’re looking back at me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I never stop thinking big, because my imagination doesn’t fit in a box.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I have conversations with the universe. It listens because I speak truth.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote:
      "Greatness isn’t something you achieve; it’s something you realize was inside you all along.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote:
      "My music is more than sound. It’s a feeling you can't put into words, but I do it anyway.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I redefine success. To me, success is when my ideas become reality, not just words.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I don’t need validation; I am validation.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "My reflection isn’t in the mirror; it’s in the world I’m shaping.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "My thoughts are art. My words are the canvas. My music is the masterpiece.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I wear my confidence like armor, and I never take it off.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I don’t think outside the box; I don’t even see the box.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I dream bigger than most people think is possible, and that’s why I succeed.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I’m not just making music; I’m making the soundtrack of my legacy.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "My ideas aren’t ahead of their time; they redefine it.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I speak in visions; that’s why not everyone understands me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },
  {
    id: uuidv4(),
    quote: "I don’t chase greatness; it gravitates towards me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Kanye West",
  },

  // Donald Trump - Fake Quotes
  {
    id: uuidv4(),
    quote: "Nobody knows the system better than me, which is why I alone can fix it.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "My energy is renewable, unlike those windmills that are killing all the birds.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I could have been an astronaut, but space isn't big enough for me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I'm so good at computers, you wouldn't believe it.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "No one reads more than me; I have the best words.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "They say time waits for no one, but time always makes an exception for me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "If I weren't president, the stock market would have crashed by now.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I make the best deals, even with the future.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I understand the climate better than any scientist.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "My handshake is the most powerful in the world.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I've mastered the art of the selfie; no one does it better.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I could negotiate peace with Mars if I wanted to.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "No one appreciates the ocean more than me; I have properties all over it.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "My tweets are considered modern poetry.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I have the most loyal followers; they'd walk through fire for me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "They say I can't fly, but I've been flying high my entire life.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I'm the best thing to happen to this country since the wheel.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "No one builds a golf course like me; the grass grows greener for me.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "I bring the weather with me; it's always sunny when I'm around.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },
  {
    id: uuidv4(),
    quote: "If I ran the Olympics, everyone would win gold.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Donald Trump",
  },

  // Charlie Sheen - Fake Quotes
  {
    id: uuidv4(),
    quote:
      "I'm on a drug called Charlie Sheen, it's not available because if you try it, you might melt.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "My life is a rollercoaster that's only going up.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "I've turned insanity into an art form.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "My shadow has a shadow; that's how intense I am.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "I drink tiger blood and adrenaline for breakfast.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "They say I’m out of control, but I’ve never been more in charge.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "Normal is not in my vocabulary.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "The mirror can't handle my reflection.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "Silence the critics by turning up the volume.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "My footsteps leave echoes in time.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "I’ve danced with chaos and came out leading.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },
  {
    id: uuidv4(),
    quote: "Some call it madness; I call it living.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Charlie Sheen",
  },

  // Ozzy Osbourne - Fake Quotes
  {
    id: uuidv4(),
    quote: "I've forgotten more about music than most will ever know.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "The stage is my cathedral; the crowd, my congregation.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "I speak fluent guitar and broken English.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "I've danced with shadows and sung with the stars.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "The bat bit me back once; fair play to the bat.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "My music doesn't just hit the ears; it hits the soul.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "I've sailed stormy seas without leaving my living room.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "I’ve been to the edge and back; the view was fantastic.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "Normality is a paved road; it's comfortable to walk, but no flowers grow on it.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
  {
    id: uuidv4(),
    quote: "I don't just perform music; I become it.",
    author: "AI-Generated",
    isReal: false,
    imitating: "Ozzy Osbourne",
  },
];
